/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s4[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s5[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s6[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[3] = {0, 0, 0};
static const casadi_int casadi_s8[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s9[7] = {0, 4, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[16] = {1., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.};

/* pendulum_car_ode_cost_ext_cost_e_fun_jac_hess:(i0[4],i1[],i2[],i3[])->(o0,o1[4],o2[4x4],o3[],o4[0x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, *w6=w+10, *w7=w+14, *w8=w+18, *w9=w+34, *w10=w+50;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #4: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #6: @6 = vertcat(@2, @3, @4, @5) */
  rr=w6;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #7: @7 = @6' */
  casadi_copy(w6, 4, w7);
  /* #8: @8 = 
  [[1, 0, 0, 0], 
   [0, 2, 0, 0], 
   [0, 0, 0, 0], 
   [0, 0, 0, 0]] */
  casadi_copy(casadi_c0, 16, w8);
  /* #9: @1 = mac(@7,@8,@1) */
  for (i=0, rr=w1; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w7+j, tt=w8+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #10: @0 = mac(@1,@6,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w6+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #11: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #12: @1 = @1' */
  /* #13: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #14: @6 = @6' */
  /* #15: @9 = @8' */
  for (i=0, rr=w9, cs=w8; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #16: @7 = mac(@6,@9,@7) */
  for (i=0, rr=w7; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #17: @7 = @7' */
  /* #18: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #19: output[1][0] = @1 */
  casadi_copy(w1, 4, res[1]);
  /* #20: @10 = zeros(4x4) */
  casadi_clear(w10, 16);
  /* #21: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #22: @0 = ones(4x1,1nz) */
  w0 = 1.;
  /* #23: {@2, NULL, NULL, NULL} = vertsplit(@0) */
  w2 = w0;
  /* #24: @11 = 00 */
  /* #25: @12 = 00 */
  /* #26: @13 = 00 */
  /* #27: @0 = vertcat(@2, @11, @12, @13) */
  rr=(&w0);
  *rr++ = w2;
  /* #28: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #29: @1 = mac(@2,@8,@1) */
  casadi_mtimes((&w2), casadi_s2, w8, casadi_s1, w1, casadi_s0, w, 0);
  /* #30: @1 = @1' */
  /* #31: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #32: @0 = @0' */
  /* #33: @7 = mac(@0,@9,@7) */
  casadi_mtimes((&w0), casadi_s2, w9, casadi_s1, w7, casadi_s0, w, 0);
  /* #34: @7 = @7' */
  /* #35: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #36: (@10[:4] = @1) */
  for (rr=w10+0, ss=w1; rr!=w10+4; rr+=1) *rr = *ss++;
  /* #37: (@10[:16:4] = @1) */
  for (rr=w10+0, ss=w1; rr!=w10+16; rr+=4) *rr = *ss++;
  /* #38: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #39: @11 = 00 */
  /* #40: @0 = ones(4x1,1nz) */
  w0 = 1.;
  /* #41: {NULL, @2, NULL, NULL} = vertsplit(@0) */
  w2 = w0;
  /* #42: @12 = 00 */
  /* #43: @13 = 00 */
  /* #44: @0 = vertcat(@11, @2, @12, @13) */
  rr=(&w0);
  *rr++ = w2;
  /* #45: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #46: @1 = mac(@2,@8,@1) */
  casadi_mtimes((&w2), casadi_s3, w8, casadi_s1, w1, casadi_s0, w, 0);
  /* #47: @1 = @1' */
  /* #48: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #49: @0 = @0' */
  /* #50: @7 = mac(@0,@9,@7) */
  casadi_mtimes((&w0), casadi_s3, w9, casadi_s1, w7, casadi_s0, w, 0);
  /* #51: @7 = @7' */
  /* #52: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #53: (@10[4:8] = @1) */
  for (rr=w10+4, ss=w1; rr!=w10+8; rr+=1) *rr = *ss++;
  /* #54: (@10[1:17:4] = @1) */
  for (rr=w10+1, ss=w1; rr!=w10+17; rr+=4) *rr = *ss++;
  /* #55: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #56: @11 = 00 */
  /* #57: @12 = 00 */
  /* #58: @0 = ones(4x1,1nz) */
  w0 = 1.;
  /* #59: {NULL, NULL, @2, NULL} = vertsplit(@0) */
  w2 = w0;
  /* #60: @13 = 00 */
  /* #61: @0 = vertcat(@11, @12, @2, @13) */
  rr=(&w0);
  *rr++ = w2;
  /* #62: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #63: @1 = mac(@2,@8,@1) */
  casadi_mtimes((&w2), casadi_s4, w8, casadi_s1, w1, casadi_s0, w, 0);
  /* #64: @1 = @1' */
  /* #65: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #66: @0 = @0' */
  /* #67: @7 = mac(@0,@9,@7) */
  casadi_mtimes((&w0), casadi_s4, w9, casadi_s1, w7, casadi_s0, w, 0);
  /* #68: @7 = @7' */
  /* #69: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #70: (@10[8:12] = @1) */
  for (rr=w10+8, ss=w1; rr!=w10+12; rr+=1) *rr = *ss++;
  /* #71: (@10[2:18:4] = @1) */
  for (rr=w10+2, ss=w1; rr!=w10+18; rr+=4) *rr = *ss++;
  /* #72: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #73: @11 = 00 */
  /* #74: @12 = 00 */
  /* #75: @13 = 00 */
  /* #76: @0 = ones(4x1,1nz) */
  w0 = 1.;
  /* #77: {NULL, NULL, NULL, @2} = vertsplit(@0) */
  w2 = w0;
  /* #78: @0 = vertcat(@11, @12, @13, @2) */
  rr=(&w0);
  *rr++ = w2;
  /* #79: @2 = @0' */
  casadi_copy((&w0), 1, (&w2));
  /* #80: @1 = mac(@2,@8,@1) */
  casadi_mtimes((&w2), casadi_s5, w8, casadi_s1, w1, casadi_s0, w, 0);
  /* #81: @1 = @1' */
  /* #82: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #83: @0 = @0' */
  /* #84: @7 = mac(@0,@9,@7) */
  casadi_mtimes((&w0), casadi_s5, w9, casadi_s1, w7, casadi_s0, w, 0);
  /* #85: @7 = @7' */
  /* #86: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #87: (@10[12:16] = @1) */
  for (rr=w10+12, ss=w1; rr!=w10+16; rr+=1) *rr = *ss++;
  /* #88: (@10[3:19:4] = @1) */
  for (rr=w10+3, ss=w1; rr!=w10+19; rr+=4) *rr = *ss++;
  /* #89: @9 = @10' */
  for (i=0, rr=w9, cs=w10; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #90: output[2][0] = @9 */
  casadi_copy(w9, 16, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s7;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s6;
    case 2: return casadi_s1;
    case 3: return casadi_s7;
    case 4: return casadi_s9;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 66;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
