/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pendulum_car_ode_cost_ext_cost_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[11] = {1, 4, 0, 1, 2, 3, 4, 0, 0, 0, 0};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[8] = {1, 4, 0, 1, 1, 1, 1, 0};
static const casadi_int casadi_s3[5] = {0, 1, 5, 9, 13};
static const casadi_int casadi_s4[8] = {1, 4, 0, 0, 1, 1, 1, 0};
static const casadi_int casadi_s5[8] = {1, 4, 0, 0, 0, 1, 1, 0};
static const casadi_int casadi_s6[8] = {1, 4, 0, 0, 0, 0, 1, 0};
static const casadi_int casadi_s7[25] = {5, 5, 0, 1, 5, 9, 13, 17, 0, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4};
static const casadi_int casadi_s8[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s9[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s10[3] = {0, 0, 0};
static const casadi_int casadi_s11[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s12[8] = {0, 5, 0, 0, 0, 0, 0, 0};

static const casadi_real casadi_c0[16] = {1., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.};

/* pendulum_car_ode_cost_ext_cost_fun_jac_hess:(i0[4],i1,i2[],i3[4])->(o0,o1[5],o2[5x5,17nz],o3[],o4[0x5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real *cs;
  casadi_real w0, *w1=w+2, w2, w3, w4, w5, *w6=w+10, *w7=w+14, *w8=w+18, *w9=w+34, *w10=w+50, *w11=w+67, *w15=w+69, *w17=w+74;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @3 = input[3][1] */
  w3 = arg[3] ? arg[3][1] : 0;
  /* #4: @4 = input[3][2] */
  w4 = arg[3] ? arg[3][2] : 0;
  /* #5: @5 = input[3][3] */
  w5 = arg[3] ? arg[3][3] : 0;
  /* #6: @6 = vertcat(@2, @3, @4, @5) */
  rr=w6;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #7: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #8: @3 = input[0][1] */
  w3 = arg[0] ? arg[0][1] : 0;
  /* #9: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #10: @5 = input[0][3] */
  w5 = arg[0] ? arg[0][3] : 0;
  /* #11: @7 = vertcat(@2, @3, @4, @5) */
  rr=w7;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  /* #12: @6 = (@6-@7) */
  for (i=0, rr=w6, cs=w7; i<4; ++i) (*rr++) -= (*cs++);
  /* #13: @7 = @6' */
  casadi_copy(w6, 4, w7);
  /* #14: @8 = 
  [[1, 0, 0, 0], 
   [0, 2, 0, 0], 
   [0, 0, 0, 0], 
   [0, 0, 0, 0]] */
  casadi_copy(casadi_c0, 16, w8);
  /* #15: @1 = mac(@7,@8,@1) */
  for (i=0, rr=w1; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w7+j, tt=w8+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #16: @0 = mac(@1,@6,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w6+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #17: @2 = 0.3 */
  w2 = 2.9999999999999999e-01;
  /* #18: @3 = input[1][0] */
  w3 = arg[1] ? arg[1][0] : 0;
  /* #19: @4 = (@2*@3) */
  w4  = (w2*w3);
  /* #20: @3 = (@4*@3) */
  w3  = (w4*w3);
  /* #21: @0 = (@0+@3) */
  w0 += w3;
  /* #22: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #23: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #24: output[1][0] = @4 */
  if (res[1]) res[1][0] = w4;
  /* #25: @1 = @1' */
  /* #26: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #27: @6 = @6' */
  /* #28: @9 = @8' */
  for (i=0, rr=w9, cs=w8; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #29: @7 = mac(@6,@9,@7) */
  for (i=0, rr=w7; i<4; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w6+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #30: @7 = @7' */
  /* #31: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #32: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #33: {@4, @0, @3, @5} = vertsplit(@1) */
  w4 = w1[0];
  w0 = w1[1];
  w3 = w1[2];
  w5 = w1[3];
  /* #34: output[1][1] = @4 */
  if (res[1]) res[1][1] = w4;
  /* #35: output[1][2] = @0 */
  if (res[1]) res[1][2] = w0;
  /* #36: output[1][3] = @3 */
  if (res[1]) res[1][3] = w3;
  /* #37: output[1][4] = @5 */
  if (res[1]) res[1][4] = w5;
  /* #38: @10 = zeros(5x5,17nz) */
  casadi_clear(w10, 17);
  /* #39: @11 = ones(5x1,2nz) */
  casadi_fill(w11, 2, 1.);
  /* #40: {@5, @3, NULL, NULL, NULL} = vertsplit(@11) */
  w5 = w11[0];
  w3 = w11[1];
  /* #41: @2 = (@2*@5) */
  w2 *= w5;
  /* #42: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #43: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #44: @12 = 00 */
  /* #45: @13 = 00 */
  /* #46: @14 = 00 */
  /* #47: @5 = vertcat(@3, @12, @13, @14) */
  rr=(&w5);
  *rr++ = w3;
  /* #48: @5 = (-@5) */
  w5 = (- w5 );
  /* #49: @3 = @5' */
  casadi_copy((&w5), 1, (&w3));
  /* #50: @1 = mac(@3,@8,@1) */
  casadi_mtimes((&w3), casadi_s2, w8, casadi_s1, w1, casadi_s0, w, 0);
  /* #51: @1 = @1' */
  /* #52: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #53: @5 = @5' */
  /* #54: @7 = mac(@5,@9,@7) */
  casadi_mtimes((&w5), casadi_s2, w9, casadi_s1, w7, casadi_s0, w, 0);
  /* #55: @7 = @7' */
  /* #56: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #57: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #58: {@5, @3, @0, @4} = vertsplit(@1) */
  w5 = w1[0];
  w3 = w1[1];
  w0 = w1[2];
  w4 = w1[3];
  /* #59: @15 = vertcat(@2, @5, @3, @0, @4) */
  rr=w15;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w0;
  *rr++ = w4;
  /* #60: (@10[:5] = @15) */
  for (rr=w10+0, ss=w15; rr!=w10+5; rr+=1) *rr = *ss++;
  /* #61: (@10[0, 1, 5, 9, 13] = @15) */
  for (cii=casadi_s3, rr=w10, ss=w15; cii!=casadi_s3+5; ++cii, ++ss) if (*cii>=0) rr[*cii] = *ss;
  /* #62: @12 = 00 */
  /* #63: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #64: @13 = 00 */
  /* #65: @2 = ones(5x1,1nz) */
  w2 = 1.;
  /* #66: {NULL, NULL, @5, NULL, NULL} = vertsplit(@2) */
  w5 = w2;
  /* #67: @14 = 00 */
  /* #68: @16 = 00 */
  /* #69: @2 = vertcat(@13, @5, @14, @16) */
  rr=(&w2);
  *rr++ = w5;
  /* #70: @2 = (-@2) */
  w2 = (- w2 );
  /* #71: @5 = @2' */
  casadi_copy((&w2), 1, (&w5));
  /* #72: @1 = mac(@5,@8,@1) */
  casadi_mtimes((&w5), casadi_s4, w8, casadi_s1, w1, casadi_s0, w, 0);
  /* #73: @1 = @1' */
  /* #74: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #75: @2 = @2' */
  /* #76: @7 = mac(@2,@9,@7) */
  casadi_mtimes((&w2), casadi_s4, w9, casadi_s1, w7, casadi_s0, w, 0);
  /* #77: @7 = @7' */
  /* #78: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #79: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #80: {@2, @5, @3, @0} = vertsplit(@1) */
  w2 = w1[0];
  w5 = w1[1];
  w3 = w1[2];
  w0 = w1[3];
  /* #81: @1 = vertcat(@12, @2, @5, @3, @0) */
  rr=w1;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w0;
  /* #82: @7 = @1[:4] */
  for (rr=w7, ss=w1+0; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #83: (@10[5:9] = @7) */
  for (rr=w10+5, ss=w7; rr!=w10+9; rr+=1) *rr = *ss++;
  /* #84: @7 = @1[:4] */
  for (rr=w7, ss=w1+0; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #85: (@10[2:18:4] = @7) */
  for (rr=w10+2, ss=w7; rr!=w10+18; rr+=4) *rr = *ss++;
  /* #86: @12 = 00 */
  /* #87: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #88: @13 = 00 */
  /* #89: @14 = 00 */
  /* #90: @2 = ones(5x1,1nz) */
  w2 = 1.;
  /* #91: {NULL, NULL, NULL, @5, NULL} = vertsplit(@2) */
  w5 = w2;
  /* #92: @16 = 00 */
  /* #93: @2 = vertcat(@13, @14, @5, @16) */
  rr=(&w2);
  *rr++ = w5;
  /* #94: @2 = (-@2) */
  w2 = (- w2 );
  /* #95: @5 = @2' */
  casadi_copy((&w2), 1, (&w5));
  /* #96: @7 = mac(@5,@8,@7) */
  casadi_mtimes((&w5), casadi_s5, w8, casadi_s1, w7, casadi_s0, w, 0);
  /* #97: @7 = @7' */
  /* #98: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #99: @2 = @2' */
  /* #100: @1 = mac(@2,@9,@1) */
  casadi_mtimes((&w2), casadi_s5, w9, casadi_s1, w1, casadi_s0, w, 0);
  /* #101: @1 = @1' */
  /* #102: @7 = (@7+@1) */
  for (i=0, rr=w7, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #103: @7 = (-@7) */
  for (i=0, rr=w7, cs=w7; i<4; ++i) *rr++ = (- *cs++ );
  /* #104: {@2, @5, @3, @0} = vertsplit(@7) */
  w2 = w7[0];
  w5 = w7[1];
  w3 = w7[2];
  w0 = w7[3];
  /* #105: @7 = vertcat(@12, @2, @5, @3, @0) */
  rr=w7;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w0;
  /* #106: @1 = @7[:4] */
  for (rr=w1, ss=w7+0; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #107: (@10[9:13] = @1) */
  for (rr=w10+9, ss=w1; rr!=w10+13; rr+=1) *rr = *ss++;
  /* #108: @1 = @7[:4] */
  for (rr=w1, ss=w7+0; ss!=w7+4; ss+=1) *rr++ = *ss;
  /* #109: (@10[3:19:4] = @1) */
  for (rr=w10+3, ss=w1; rr!=w10+19; rr+=4) *rr = *ss++;
  /* #110: @12 = 00 */
  /* #111: @1 = zeros(1x4) */
  casadi_clear(w1, 4);
  /* #112: @13 = 00 */
  /* #113: @14 = 00 */
  /* #114: @16 = 00 */
  /* #115: @2 = ones(5x1,1nz) */
  w2 = 1.;
  /* #116: {NULL, NULL, NULL, NULL, @5} = vertsplit(@2) */
  w5 = w2;
  /* #117: @2 = vertcat(@13, @14, @16, @5) */
  rr=(&w2);
  *rr++ = w5;
  /* #118: @2 = (-@2) */
  w2 = (- w2 );
  /* #119: @5 = @2' */
  casadi_copy((&w2), 1, (&w5));
  /* #120: @1 = mac(@5,@8,@1) */
  casadi_mtimes((&w5), casadi_s6, w8, casadi_s1, w1, casadi_s0, w, 0);
  /* #121: @1 = @1' */
  /* #122: @7 = zeros(1x4) */
  casadi_clear(w7, 4);
  /* #123: @2 = @2' */
  /* #124: @7 = mac(@2,@9,@7) */
  casadi_mtimes((&w2), casadi_s6, w9, casadi_s1, w7, casadi_s0, w, 0);
  /* #125: @7 = @7' */
  /* #126: @1 = (@1+@7) */
  for (i=0, rr=w1, cs=w7; i<4; ++i) (*rr++) += (*cs++);
  /* #127: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #128: {@2, @5, @3, @0} = vertsplit(@1) */
  w2 = w1[0];
  w5 = w1[1];
  w3 = w1[2];
  w0 = w1[3];
  /* #129: @1 = vertcat(@12, @2, @5, @3, @0) */
  rr=w1;
  *rr++ = w2;
  *rr++ = w5;
  *rr++ = w3;
  *rr++ = w0;
  /* #130: @7 = @1[:4] */
  for (rr=w7, ss=w1+0; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #131: (@10[13:17] = @7) */
  for (rr=w10+13, ss=w7; rr!=w10+17; rr+=1) *rr = *ss++;
  /* #132: @7 = @1[:4] */
  for (rr=w7, ss=w1+0; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #133: (@10[4:20:4] = @7) */
  for (rr=w10+4, ss=w7; rr!=w10+20; rr+=4) *rr = *ss++;
  /* #134: @17 = @10' */
  casadi_trans(w10,casadi_s7, w17, casadi_s7, iw);
  /* #135: output[2][0] = @17 */
  casadi_copy(w17, 17, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_cost_ext_cost_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_cost_ext_cost_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_cost_ext_cost_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_cost_ext_cost_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_cost_ext_cost_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_cost_ext_cost_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_cost_ext_cost_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_cost_ext_cost_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pendulum_car_ode_cost_ext_cost_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pendulum_car_ode_cost_ext_cost_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real pendulum_car_ode_cost_ext_cost_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_car_ode_cost_ext_cost_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_car_ode_cost_ext_cost_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_car_ode_cost_ext_cost_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s9;
    case 2: return casadi_s10;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_car_ode_cost_ext_cost_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s11;
    case 2: return casadi_s7;
    case 3: return casadi_s10;
    case 4: return casadi_s12;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_cost_ext_cost_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 10;
  if (sz_iw) *sz_iw = 6;
  if (sz_w) *sz_w = 91;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
