/* This file was automatically generated by CasADi 3.6.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pendulum_car_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[8] = {5, 1, 0, 4, 1, 2, 3, 4};

/* pendulum_car_ode_expl_vde_adj:(i0[4],i1[4],i2,i3[])->(o0[5x1,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1, w2, *w3=w+3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, w26, w27;
  /* #0: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #1: @1 = cos(@0) */
  w1 = cos( w0 );
  /* #2: @2 = 10.791 */
  w2 = 1.0791000000000002e+01;
  /* #3: @3 = input[1][0] */
  casadi_copy(arg[1], 4, w3);
  /* #4: {@4, @5, @6, @7} = vertsplit(@3) */
  w4 = w3[0];
  w5 = w3[1];
  w6 = w3[2];
  w7 = w3[3];
  /* #5: @8 = 0.8 */
  w8 = 8.0000000000000004e-01;
  /* #6: @9 = 1.1 */
  w9 = 1.1000000000000001e+00;
  /* #7: @10 = 0.1 */
  w10 = 1.0000000000000001e-01;
  /* #8: @11 = cos(@0) */
  w11 = cos( w0 );
  /* #9: @12 = (@10*@11) */
  w12  = (w10*w11);
  /* #10: @13 = (@12*@11) */
  w13  = (w12*w11);
  /* #11: @9 = (@9-@13) */
  w9 -= w13;
  /* #12: @13 = (@8*@9) */
  w13  = (w8*w9);
  /* #13: @14 = (@7/@13) */
  w14  = (w7/w13);
  /* #14: @15 = (@2*@14) */
  w15  = (w2*w14);
  /* #15: @16 = -0.08 */
  w16 = -8.0000000000000016e-02;
  /* #16: @17 = (@16*@11) */
  w17  = (w16*w11);
  /* #17: @18 = input[0][3] */
  w18 = arg[0] ? arg[0][3] : 0;
  /* #18: @19 = (@18*@14) */
  w19  = (w18*w14);
  /* #19: @20 = (@18*@19) */
  w20  = (w18*w19);
  /* #20: @21 = (@17*@20) */
  w21  = (w17*w20);
  /* #21: @15 = (@15+@21) */
  w15 += w21;
  /* #22: @21 = 0.981 */
  w21 = 9.8100000000000009e-01;
  /* #23: @22 = (@21*@11) */
  w22  = (w21*w11);
  /* #24: @23 = (@6/@9) */
  w23  = (w6/w9);
  /* #25: @24 = (@22*@23) */
  w24  = (w22*w23);
  /* #26: @15 = (@15+@24) */
  w15 += w24;
  /* #27: @24 = -0.08 */
  w24 = -8.0000000000000016e-02;
  /* #28: @25 = (@18*@23) */
  w25  = (w18*w23);
  /* #29: @26 = (@18*@25) */
  w26  = (w18*w25);
  /* #30: @26 = (@24*@26) */
  w26  = (w24*w26);
  /* #31: @15 = (@15+@26) */
  w15 += w26;
  /* #32: @1 = (@1*@15) */
  w1 *= w15;
  /* #33: @15 = sin(@0) */
  w15 = sin( w0 );
  /* #34: @26 = input[2][0] */
  w26 = arg[2] ? arg[2][0] : 0;
  /* #35: @27 = (@26*@14) */
  w27  = (w26*w14);
  /* #36: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #37: @20 = (@0*@20) */
  w20  = (w0*w20);
  /* #38: @16 = (@16*@20) */
  w16 *= w20;
  /* #39: @27 = (@27+@16) */
  w27 += w16;
  /* #40: @24 = (@24*@0) */
  w24 *= w0;
  /* #41: @16 = (@24*@18) */
  w16  = (w24*w18);
  /* #42: @20 = (@16*@18) */
  w20  = (w16*w18);
  /* #43: @22 = (@22*@0) */
  w22 *= w0;
  /* #44: @20 = (@20+@22) */
  w20 += w22;
  /* #45: @20 = (@20+@26) */
  w20 += w26;
  /* #46: @20 = (@20/@9) */
  w20 /= w9;
  /* #47: @20 = (@20/@9) */
  w20 /= w9;
  /* #48: @20 = (@20*@6) */
  w20 *= w6;
  /* #49: @20 = (-@20) */
  w20 = (- w20 );
  /* #50: @17 = (@17*@0) */
  w17 *= w0;
  /* #51: @6 = (@17*@18) */
  w6  = (w17*w18);
  /* #52: @18 = (@6*@18) */
  w18  = (w6*w18);
  /* #53: @26 = (@26*@11) */
  w26 *= w11;
  /* #54: @18 = (@18+@26) */
  w18 += w26;
  /* #55: @2 = (@2*@0) */
  w2 *= w0;
  /* #56: @18 = (@18+@2) */
  w18 += w2;
  /* #57: @18 = (@18/@13) */
  w18 /= w13;
  /* #58: @18 = (@18/@13) */
  w18 /= w13;
  /* #59: @18 = (@18*@7) */
  w18 *= w7;
  /* #60: @8 = (@8*@18) */
  w8 *= w18;
  /* #61: @20 = (@20-@8) */
  w20 -= w8;
  /* #62: @12 = (@12*@20) */
  w12 *= w20;
  /* #63: @27 = (@27-@12) */
  w27 -= w12;
  /* #64: @20 = (@11*@20) */
  w20  = (w11*w20);
  /* #65: @10 = (@10*@20) */
  w10 *= w20;
  /* #66: @27 = (@27-@10) */
  w27 -= w10;
  /* #67: @0 = (@0*@23) */
  w0 *= w23;
  /* #68: @21 = (@21*@0) */
  w21 *= w0;
  /* #69: @27 = (@27+@21) */
  w27 += w21;
  /* #70: @15 = (@15*@27) */
  w15 *= w27;
  /* #71: @1 = (@1-@15) */
  w1 -= w15;
  /* #72: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #73: output[0][1] = @4 */
  if (res[0]) res[0][1] = w4;
  /* #74: @6 = (@6*@14) */
  w6 *= w14;
  /* #75: @17 = (@17*@19) */
  w17 *= w19;
  /* #76: @6 = (@6+@17) */
  w6 += w17;
  /* #77: @16 = (@16*@23) */
  w16 *= w23;
  /* #78: @6 = (@6+@16) */
  w6 += w16;
  /* #79: @24 = (@24*@25) */
  w24 *= w25;
  /* #80: @6 = (@6+@24) */
  w6 += w24;
  /* #81: @6 = (@6+@5) */
  w6 += w5;
  /* #82: output[0][2] = @6 */
  if (res[0]) res[0][2] = w6;
  /* #83: @11 = (@11*@14) */
  w11 *= w14;
  /* #84: @11 = (@11+@23) */
  w11 += w23;
  /* #85: output[0][3] = @11 */
  if (res[0]) res[0][3] = w11;
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pendulum_car_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int pendulum_car_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real pendulum_car_ode_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_car_ode_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_car_ode_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_car_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_car_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 31;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
