/* This file was automatically generated by CasADi 3.6.1.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) pendulum_car_ode_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_densify CASADI_PREFIX(densify)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

#define CASADI_CAST(x,y) ((x) y)

void casadi_densify(const casadi_real* x, const casadi_int* sp_x, casadi_real* y, casadi_int tr) {
  casadi_int nrow_x, ncol_x, i, el;
  const casadi_int *colind_x, *row_x;
  if (!y) return;
  nrow_x = sp_x[0]; ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x+ncol_x+3;
  casadi_clear(y, nrow_x*ncol_x);
  if (!x) return;
  if (tr) {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[i + row_x[el]*ncol_x] = CASADI_CAST(casadi_real, *x++);
      }
    }
  } else {
    for (i=0; i<ncol_x; ++i) {
      for (el=colind_x[i]; el!=colind_x[i+1]; ++el) {
        y[row_x[el]] = CASADI_CAST(casadi_real, *x++);
      }
      y += nrow_x;
    }
  }
}

static const casadi_int casadi_s0[6] = {4, 1, 0, 2, 2, 3};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[3] = {0, 0, 0};

/* pendulum_car_ode_expl_vde_forw:(i0[4],i1[4x4],i2[4],i3,i4[])->(o0[4],o1[4x4],o2[4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+22, *w23=w+38, *w24=w+42, *w25=w+46, *w26=w+50, w27, w28, w29, w30, w31, w32, w33, w34, w35, w36, *w37=w+64, *w40=w+66, *w41=w+68;
  /* #0: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #1: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #2: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #3: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #4: @1 = -0.08 */
  w1 = -8.0000000000000016e-02;
  /* #5: @2 = input[0][1] */
  w2 = arg[0] ? arg[0][1] : 0;
  /* #6: @3 = sin(@2) */
  w3 = sin( w2 );
  /* #7: @4 = (@1*@3) */
  w4  = (w1*w3);
  /* #8: @5 = (@4*@0) */
  w5  = (w4*w0);
  /* #9: @6 = (@5*@0) */
  w6  = (w5*w0);
  /* #10: @7 = 0.981 */
  w7 = 9.8100000000000009e-01;
  /* #11: @8 = cos(@2) */
  w8 = cos( w2 );
  /* #12: @9 = (@7*@8) */
  w9  = (w7*w8);
  /* #13: @10 = (@9*@3) */
  w10  = (w9*w3);
  /* #14: @6 = (@6+@10) */
  w6 += w10;
  /* #15: @10 = input[3][0] */
  w10 = arg[3] ? arg[3][0] : 0;
  /* #16: @6 = (@6+@10) */
  w6 += w10;
  /* #17: @11 = 1.1 */
  w11 = 1.1000000000000001e+00;
  /* #18: @12 = 0.1 */
  w12 = 1.0000000000000001e-01;
  /* #19: @13 = (@12*@8) */
  w13  = (w12*w8);
  /* #20: @14 = (@13*@8) */
  w14  = (w13*w8);
  /* #21: @11 = (@11-@14) */
  w11 -= w14;
  /* #22: @6 = (@6/@11) */
  w6 /= w11;
  /* #23: output[0][2] = @6 */
  if (res[0]) res[0][2] = w6;
  /* #24: @14 = -0.08 */
  w14 = -8.0000000000000016e-02;
  /* #25: @15 = (@14*@8) */
  w15  = (w14*w8);
  /* #26: @16 = (@15*@3) */
  w16  = (w15*w3);
  /* #27: @17 = (@16*@0) */
  w17  = (w16*w0);
  /* #28: @18 = (@17*@0) */
  w18  = (w17*w0);
  /* #29: @19 = (@10*@8) */
  w19  = (w10*w8);
  /* #30: @18 = (@18+@19) */
  w18 += w19;
  /* #31: @19 = 10.791 */
  w19 = 1.0791000000000002e+01;
  /* #32: @20 = (@19*@3) */
  w20  = (w19*w3);
  /* #33: @18 = (@18+@20) */
  w18 += w20;
  /* #34: @20 = 0.8 */
  w20 = 8.0000000000000004e-01;
  /* #35: @21 = (@20*@11) */
  w21  = (w20*w11);
  /* #36: @18 = (@18/@21) */
  w18 /= w21;
  /* #37: output[0][3] = @18 */
  if (res[0]) res[0][3] = w18;
  /* #38: @22 = input[1][0] */
  casadi_copy(arg[1], 16, w22);
  /* #39: {@23, @24, @25, @26} = horzsplit(@22) */
  casadi_copy(w22, 4, w23);
  casadi_copy(w22+4, 4, w24);
  casadi_copy(w22+8, 4, w25);
  casadi_copy(w22+12, 4, w26);
  /* #40: {NULL, @27, @28, @29} = vertsplit(@23) */
  w27 = w23[1];
  w28 = w23[2];
  w29 = w23[3];
  /* #41: output[1][0] = @28 */
  if (res[1]) res[1][0] = w28;
  /* #42: output[1][1] = @29 */
  if (res[1]) res[1][1] = w29;
  /* #43: @28 = cos(@2) */
  w28 = cos( w2 );
  /* #44: @30 = (@28*@27) */
  w30  = (w28*w27);
  /* #45: @31 = (@1*@30) */
  w31  = (w1*w30);
  /* #46: @31 = (@0*@31) */
  w31  = (w0*w31);
  /* #47: @32 = (@4*@29) */
  w32  = (w4*w29);
  /* #48: @31 = (@31+@32) */
  w31 += w32;
  /* #49: @31 = (@0*@31) */
  w31  = (w0*w31);
  /* #50: @32 = (@5*@29) */
  w32  = (w5*w29);
  /* #51: @31 = (@31+@32) */
  w31 += w32;
  /* #52: @32 = (@9*@30) */
  w32  = (w9*w30);
  /* #53: @33 = sin(@2) */
  w33 = sin( w2 );
  /* #54: @27 = (@33*@27) */
  w27  = (w33*w27);
  /* #55: @34 = (@7*@27) */
  w34  = (w7*w27);
  /* #56: @34 = (@3*@34) */
  w34  = (w3*w34);
  /* #57: @32 = (@32-@34) */
  w32 -= w34;
  /* #58: @31 = (@31+@32) */
  w31 += w32;
  /* #59: @31 = (@31/@11) */
  w31 /= w11;
  /* #60: @32 = (@6/@11) */
  w32  = (w6/w11);
  /* #61: @34 = (@13*@27) */
  w34  = (w13*w27);
  /* #62: @34 = (-@34) */
  w34 = (- w34 );
  /* #63: @35 = (@12*@27) */
  w35  = (w12*w27);
  /* #64: @35 = (@8*@35) */
  w35  = (w8*w35);
  /* #65: @34 = (@34-@35) */
  w34 -= w35;
  /* #66: @35 = (@32*@34) */
  w35  = (w32*w34);
  /* #67: @31 = (@31+@35) */
  w31 += w35;
  /* #68: output[1][2] = @31 */
  if (res[1]) res[1][2] = w31;
  /* #69: @31 = (@15*@30) */
  w31  = (w15*w30);
  /* #70: @35 = (@14*@27) */
  w35  = (w14*w27);
  /* #71: @35 = (@3*@35) */
  w35  = (w3*w35);
  /* #72: @31 = (@31-@35) */
  w31 -= w35;
  /* #73: @31 = (@0*@31) */
  w31  = (w0*w31);
  /* #74: @35 = (@16*@29) */
  w35  = (w16*w29);
  /* #75: @31 = (@31+@35) */
  w31 += w35;
  /* #76: @31 = (@0*@31) */
  w31  = (w0*w31);
  /* #77: @29 = (@17*@29) */
  w29  = (w17*w29);
  /* #78: @31 = (@31+@29) */
  w31 += w29;
  /* #79: @27 = (@10*@27) */
  w27  = (w10*w27);
  /* #80: @31 = (@31-@27) */
  w31 -= w27;
  /* #81: @30 = (@19*@30) */
  w30  = (w19*w30);
  /* #82: @31 = (@31+@30) */
  w31 += w30;
  /* #83: @31 = (@31/@21) */
  w31 /= w21;
  /* #84: @30 = (@18/@21) */
  w30  = (w18/w21);
  /* #85: @34 = (@20*@34) */
  w34  = (w20*w34);
  /* #86: @34 = (@30*@34) */
  w34  = (w30*w34);
  /* #87: @31 = (@31+@34) */
  w31 += w34;
  /* #88: output[1][3] = @31 */
  if (res[1]) res[1][3] = w31;
  /* #89: {NULL, @31, @34, @27} = vertsplit(@24) */
  w31 = w24[1];
  w34 = w24[2];
  w27 = w24[3];
  /* #90: output[1][4] = @34 */
  if (res[1]) res[1][4] = w34;
  /* #91: output[1][5] = @27 */
  if (res[1]) res[1][5] = w27;
  /* #92: @34 = (@28*@31) */
  w34  = (w28*w31);
  /* #93: @29 = (@1*@34) */
  w29  = (w1*w34);
  /* #94: @29 = (@0*@29) */
  w29  = (w0*w29);
  /* #95: @35 = (@4*@27) */
  w35  = (w4*w27);
  /* #96: @29 = (@29+@35) */
  w29 += w35;
  /* #97: @29 = (@0*@29) */
  w29  = (w0*w29);
  /* #98: @35 = (@5*@27) */
  w35  = (w5*w27);
  /* #99: @29 = (@29+@35) */
  w29 += w35;
  /* #100: @35 = (@9*@34) */
  w35  = (w9*w34);
  /* #101: @31 = (@33*@31) */
  w31  = (w33*w31);
  /* #102: @36 = (@7*@31) */
  w36  = (w7*w31);
  /* #103: @36 = (@3*@36) */
  w36  = (w3*w36);
  /* #104: @35 = (@35-@36) */
  w35 -= w36;
  /* #105: @29 = (@29+@35) */
  w29 += w35;
  /* #106: @29 = (@29/@11) */
  w29 /= w11;
  /* #107: @35 = (@13*@31) */
  w35  = (w13*w31);
  /* #108: @35 = (-@35) */
  w35 = (- w35 );
  /* #109: @36 = (@12*@31) */
  w36  = (w12*w31);
  /* #110: @36 = (@8*@36) */
  w36  = (w8*w36);
  /* #111: @35 = (@35-@36) */
  w35 -= w36;
  /* #112: @36 = (@32*@35) */
  w36  = (w32*w35);
  /* #113: @29 = (@29+@36) */
  w29 += w36;
  /* #114: output[1][6] = @29 */
  if (res[1]) res[1][6] = w29;
  /* #115: @29 = (@15*@34) */
  w29  = (w15*w34);
  /* #116: @36 = (@14*@31) */
  w36  = (w14*w31);
  /* #117: @36 = (@3*@36) */
  w36  = (w3*w36);
  /* #118: @29 = (@29-@36) */
  w29 -= w36;
  /* #119: @29 = (@0*@29) */
  w29  = (w0*w29);
  /* #120: @36 = (@16*@27) */
  w36  = (w16*w27);
  /* #121: @29 = (@29+@36) */
  w29 += w36;
  /* #122: @29 = (@0*@29) */
  w29  = (w0*w29);
  /* #123: @27 = (@17*@27) */
  w27  = (w17*w27);
  /* #124: @29 = (@29+@27) */
  w29 += w27;
  /* #125: @31 = (@10*@31) */
  w31  = (w10*w31);
  /* #126: @29 = (@29-@31) */
  w29 -= w31;
  /* #127: @34 = (@19*@34) */
  w34  = (w19*w34);
  /* #128: @29 = (@29+@34) */
  w29 += w34;
  /* #129: @29 = (@29/@21) */
  w29 /= w21;
  /* #130: @35 = (@20*@35) */
  w35  = (w20*w35);
  /* #131: @35 = (@30*@35) */
  w35  = (w30*w35);
  /* #132: @29 = (@29+@35) */
  w29 += w35;
  /* #133: output[1][7] = @29 */
  if (res[1]) res[1][7] = w29;
  /* #134: {NULL, @29, @35, @34} = vertsplit(@25) */
  w29 = w25[1];
  w35 = w25[2];
  w34 = w25[3];
  /* #135: output[1][8] = @35 */
  if (res[1]) res[1][8] = w35;
  /* #136: output[1][9] = @34 */
  if (res[1]) res[1][9] = w34;
  /* #137: @35 = (@28*@29) */
  w35  = (w28*w29);
  /* #138: @31 = (@1*@35) */
  w31  = (w1*w35);
  /* #139: @31 = (@0*@31) */
  w31  = (w0*w31);
  /* #140: @27 = (@4*@34) */
  w27  = (w4*w34);
  /* #141: @31 = (@31+@27) */
  w31 += w27;
  /* #142: @31 = (@0*@31) */
  w31  = (w0*w31);
  /* #143: @27 = (@5*@34) */
  w27  = (w5*w34);
  /* #144: @31 = (@31+@27) */
  w31 += w27;
  /* #145: @27 = (@9*@35) */
  w27  = (w9*w35);
  /* #146: @29 = (@33*@29) */
  w29  = (w33*w29);
  /* #147: @36 = (@7*@29) */
  w36  = (w7*w29);
  /* #148: @36 = (@3*@36) */
  w36  = (w3*w36);
  /* #149: @27 = (@27-@36) */
  w27 -= w36;
  /* #150: @31 = (@31+@27) */
  w31 += w27;
  /* #151: @31 = (@31/@11) */
  w31 /= w11;
  /* #152: @27 = (@13*@29) */
  w27  = (w13*w29);
  /* #153: @27 = (-@27) */
  w27 = (- w27 );
  /* #154: @36 = (@12*@29) */
  w36  = (w12*w29);
  /* #155: @36 = (@8*@36) */
  w36  = (w8*w36);
  /* #156: @27 = (@27-@36) */
  w27 -= w36;
  /* #157: @36 = (@32*@27) */
  w36  = (w32*w27);
  /* #158: @31 = (@31+@36) */
  w31 += w36;
  /* #159: output[1][10] = @31 */
  if (res[1]) res[1][10] = w31;
  /* #160: @31 = (@15*@35) */
  w31  = (w15*w35);
  /* #161: @36 = (@14*@29) */
  w36  = (w14*w29);
  /* #162: @36 = (@3*@36) */
  w36  = (w3*w36);
  /* #163: @31 = (@31-@36) */
  w31 -= w36;
  /* #164: @31 = (@0*@31) */
  w31  = (w0*w31);
  /* #165: @36 = (@16*@34) */
  w36  = (w16*w34);
  /* #166: @31 = (@31+@36) */
  w31 += w36;
  /* #167: @31 = (@0*@31) */
  w31  = (w0*w31);
  /* #168: @34 = (@17*@34) */
  w34  = (w17*w34);
  /* #169: @31 = (@31+@34) */
  w31 += w34;
  /* #170: @29 = (@10*@29) */
  w29  = (w10*w29);
  /* #171: @31 = (@31-@29) */
  w31 -= w29;
  /* #172: @35 = (@19*@35) */
  w35  = (w19*w35);
  /* #173: @31 = (@31+@35) */
  w31 += w35;
  /* #174: @31 = (@31/@21) */
  w31 /= w21;
  /* #175: @27 = (@20*@27) */
  w27  = (w20*w27);
  /* #176: @27 = (@30*@27) */
  w27  = (w30*w27);
  /* #177: @31 = (@31+@27) */
  w31 += w27;
  /* #178: output[1][11] = @31 */
  if (res[1]) res[1][11] = w31;
  /* #179: {NULL, @31, @27, @35} = vertsplit(@26) */
  w31 = w26[1];
  w27 = w26[2];
  w35 = w26[3];
  /* #180: output[1][12] = @27 */
  if (res[1]) res[1][12] = w27;
  /* #181: output[1][13] = @35 */
  if (res[1]) res[1][13] = w35;
  /* #182: @28 = (@28*@31) */
  w28 *= w31;
  /* #183: @27 = (@1*@28) */
  w27  = (w1*w28);
  /* #184: @27 = (@0*@27) */
  w27  = (w0*w27);
  /* #185: @29 = (@4*@35) */
  w29  = (w4*w35);
  /* #186: @27 = (@27+@29) */
  w27 += w29;
  /* #187: @27 = (@0*@27) */
  w27  = (w0*w27);
  /* #188: @29 = (@5*@35) */
  w29  = (w5*w35);
  /* #189: @27 = (@27+@29) */
  w27 += w29;
  /* #190: @29 = (@9*@28) */
  w29  = (w9*w28);
  /* #191: @33 = (@33*@31) */
  w33 *= w31;
  /* #192: @31 = (@7*@33) */
  w31  = (w7*w33);
  /* #193: @31 = (@3*@31) */
  w31  = (w3*w31);
  /* #194: @29 = (@29-@31) */
  w29 -= w31;
  /* #195: @27 = (@27+@29) */
  w27 += w29;
  /* #196: @27 = (@27/@11) */
  w27 /= w11;
  /* #197: @29 = (@13*@33) */
  w29  = (w13*w33);
  /* #198: @29 = (-@29) */
  w29 = (- w29 );
  /* #199: @31 = (@12*@33) */
  w31  = (w12*w33);
  /* #200: @31 = (@8*@31) */
  w31  = (w8*w31);
  /* #201: @29 = (@29-@31) */
  w29 -= w31;
  /* #202: @32 = (@32*@29) */
  w32 *= w29;
  /* #203: @27 = (@27+@32) */
  w27 += w32;
  /* #204: output[1][14] = @27 */
  if (res[1]) res[1][14] = w27;
  /* #205: @27 = (@15*@28) */
  w27  = (w15*w28);
  /* #206: @32 = (@14*@33) */
  w32  = (w14*w33);
  /* #207: @32 = (@3*@32) */
  w32  = (w3*w32);
  /* #208: @27 = (@27-@32) */
  w27 -= w32;
  /* #209: @27 = (@0*@27) */
  w27  = (w0*w27);
  /* #210: @32 = (@16*@35) */
  w32  = (w16*w35);
  /* #211: @27 = (@27+@32) */
  w27 += w32;
  /* #212: @27 = (@0*@27) */
  w27  = (w0*w27);
  /* #213: @35 = (@17*@35) */
  w35  = (w17*w35);
  /* #214: @27 = (@27+@35) */
  w27 += w35;
  /* #215: @33 = (@10*@33) */
  w33  = (w10*w33);
  /* #216: @27 = (@27-@33) */
  w27 -= w33;
  /* #217: @28 = (@19*@28) */
  w28  = (w19*w28);
  /* #218: @27 = (@27+@28) */
  w27 += w28;
  /* #219: @27 = (@27/@21) */
  w27 /= w21;
  /* #220: @29 = (@20*@29) */
  w29  = (w20*w29);
  /* #221: @30 = (@30*@29) */
  w30 *= w29;
  /* #222: @27 = (@27+@30) */
  w27 += w30;
  /* #223: output[1][15] = @27 */
  if (res[1]) res[1][15] = w27;
  /* #224: @37 = zeros(1x4,2nz) */
  casadi_clear(w37, 2);
  /* #225: @38 = 00 */
  /* #226: @39 = 00 */
  /* #227: @27 = (1./@11) */
  w27 = (1./ w11 );
  /* #228: @30 = (@8/@21) */
  w30  = (w8/w21);
  /* #229: @40 = vertcat(@38, @39, @27, @30) */
  rr=w40;
  *rr++ = w27;
  *rr++ = w30;
  /* #230: @41 = @40[:2] */
  for (rr=w41, ss=w40+0; ss!=w40+2; ss+=1) *rr++ = *ss;
  /* #231: (@37[:2] = @41) */
  for (rr=w37+0, ss=w41; rr!=w37+2; rr+=1) *rr = *ss++;
  /* #232: @37 = @37' */
  /* #233: @26 = dense(@37) */
  casadi_densify(w37, casadi_s0, w26, 0);
  /* #234: @25 = input[2][0] */
  casadi_copy(arg[2], 4, w25);
  /* #235: {NULL, @27, @30, @29} = vertsplit(@25) */
  w27 = w25[1];
  w30 = w25[2];
  w29 = w25[3];
  /* #236: @28 = cos(@2) */
  w28 = cos( w2 );
  /* #237: @28 = (@28*@27) */
  w28 *= w27;
  /* #238: @1 = (@1*@28) */
  w1 *= w28;
  /* #239: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #240: @4 = (@4*@29) */
  w4 *= w29;
  /* #241: @1 = (@1+@4) */
  w1 += w4;
  /* #242: @1 = (@0*@1) */
  w1  = (w0*w1);
  /* #243: @5 = (@5*@29) */
  w5 *= w29;
  /* #244: @1 = (@1+@5) */
  w1 += w5;
  /* #245: @9 = (@9*@28) */
  w9 *= w28;
  /* #246: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #247: @2 = (@2*@27) */
  w2 *= w27;
  /* #248: @7 = (@7*@2) */
  w7 *= w2;
  /* #249: @7 = (@3*@7) */
  w7  = (w3*w7);
  /* #250: @9 = (@9-@7) */
  w9 -= w7;
  /* #251: @1 = (@1+@9) */
  w1 += w9;
  /* #252: @1 = (@1/@11) */
  w1 /= w11;
  /* #253: @6 = (@6/@11) */
  w6 /= w11;
  /* #254: @13 = (@13*@2) */
  w13 *= w2;
  /* #255: @13 = (-@13) */
  w13 = (- w13 );
  /* #256: @12 = (@12*@2) */
  w12 *= w2;
  /* #257: @8 = (@8*@12) */
  w8 *= w12;
  /* #258: @13 = (@13-@8) */
  w13 -= w8;
  /* #259: @6 = (@6*@13) */
  w6 *= w13;
  /* #260: @1 = (@1+@6) */
  w1 += w6;
  /* #261: @15 = (@15*@28) */
  w15 *= w28;
  /* #262: @14 = (@14*@2) */
  w14 *= w2;
  /* #263: @3 = (@3*@14) */
  w3 *= w14;
  /* #264: @15 = (@15-@3) */
  w15 -= w3;
  /* #265: @15 = (@0*@15) */
  w15  = (w0*w15);
  /* #266: @16 = (@16*@29) */
  w16 *= w29;
  /* #267: @15 = (@15+@16) */
  w15 += w16;
  /* #268: @0 = (@0*@15) */
  w0 *= w15;
  /* #269: @17 = (@17*@29) */
  w17 *= w29;
  /* #270: @0 = (@0+@17) */
  w0 += w17;
  /* #271: @10 = (@10*@2) */
  w10 *= w2;
  /* #272: @0 = (@0-@10) */
  w0 -= w10;
  /* #273: @19 = (@19*@28) */
  w19 *= w28;
  /* #274: @0 = (@0+@19) */
  w0 += w19;
  /* #275: @0 = (@0/@21) */
  w0 /= w21;
  /* #276: @18 = (@18/@21) */
  w18 /= w21;
  /* #277: @20 = (@20*@13) */
  w20 *= w13;
  /* #278: @18 = (@18*@20) */
  w18 *= w20;
  /* #279: @0 = (@0+@18) */
  w0 += w18;
  /* #280: @25 = vertcat(@30, @29, @1, @0) */
  rr=w25;
  *rr++ = w30;
  *rr++ = w29;
  *rr++ = w1;
  *rr++ = w0;
  /* #281: @26 = (@26+@25) */
  for (i=0, rr=w26, cs=w25; i<4; ++i) (*rr++) += (*cs++);
  /* #282: output[2][0] = @26 */
  casadi_copy(w26, 4, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void pendulum_car_ode_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int pendulum_car_ode_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int pendulum_car_ode_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real pendulum_car_ode_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_car_ode_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* pendulum_car_ode_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_car_ode_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* pendulum_car_ode_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    case 1: return casadi_s2;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int pendulum_car_ode_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 70;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
